notification:
  email:
    recipients:
      - wcmeng@ctrip.com
      - oytmfc@163.com
    on_success: always
    on_failure: always
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2

before_script:


script:
   /usr/bin/true
  
before_install:

after_success:

branches:
  only:
    - master
